// source: gaia/usc/v1beta1/genesis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var gaia_usc_v1beta1_usc_pb = require('../../../gaia/usc/v1beta1/usc_pb.js');
goog.object.extend(proto, gaia_usc_v1beta1_usc_pb);
goog.exportSymbol('proto.gaia.usc.v1beta1.GenesisState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.GenesisState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gaia.usc.v1beta1.GenesisState.repeatedFields_, null);
};
goog.inherits(proto.gaia.usc.v1beta1.GenesisState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.GenesisState.displayName = 'proto.gaia.usc.v1beta1.GenesisState';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gaia.usc.v1beta1.GenesisState.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.GenesisState.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.GenesisState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.GenesisState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.GenesisState.toObject = function(includeInstance, msg) {
  var f, obj = {
    params: (f = msg.getParams()) && gaia_usc_v1beta1_usc_pb.Params.toObject(includeInstance, f),
    redeemEntriesList: jspb.Message.toObjectList(msg.getRedeemEntriesList(),
    gaia_usc_v1beta1_usc_pb.RedeemEntry.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.GenesisState}
 */
proto.gaia.usc.v1beta1.GenesisState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.GenesisState;
  return proto.gaia.usc.v1beta1.GenesisState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.GenesisState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.GenesisState}
 */
proto.gaia.usc.v1beta1.GenesisState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new gaia_usc_v1beta1_usc_pb.Params;
      reader.readMessage(value,gaia_usc_v1beta1_usc_pb.Params.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    case 2:
      var value = new gaia_usc_v1beta1_usc_pb.RedeemEntry;
      reader.readMessage(value,gaia_usc_v1beta1_usc_pb.RedeemEntry.deserializeBinaryFromReader);
      msg.addRedeemEntries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.GenesisState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.GenesisState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.GenesisState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.GenesisState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      gaia_usc_v1beta1_usc_pb.Params.serializeBinaryToWriter
    );
  }
  f = message.getRedeemEntriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      gaia_usc_v1beta1_usc_pb.RedeemEntry.serializeBinaryToWriter
    );
  }
};


/**
 * optional Params params = 1;
 * @return {?proto.gaia.usc.v1beta1.Params}
 */
proto.gaia.usc.v1beta1.GenesisState.prototype.getParams = function() {
  return /** @type{?proto.gaia.usc.v1beta1.Params} */ (
    jspb.Message.getWrapperField(this, gaia_usc_v1beta1_usc_pb.Params, 1));
};


/**
 * @param {?proto.gaia.usc.v1beta1.Params|undefined} value
 * @return {!proto.gaia.usc.v1beta1.GenesisState} returns this
*/
proto.gaia.usc.v1beta1.GenesisState.prototype.setParams = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gaia.usc.v1beta1.GenesisState} returns this
 */
proto.gaia.usc.v1beta1.GenesisState.prototype.clearParams = function() {
  return this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gaia.usc.v1beta1.GenesisState.prototype.hasParams = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated RedeemEntry redeem_entries = 2;
 * @return {!Array<!proto.gaia.usc.v1beta1.RedeemEntry>}
 */
proto.gaia.usc.v1beta1.GenesisState.prototype.getRedeemEntriesList = function() {
  return /** @type{!Array<!proto.gaia.usc.v1beta1.RedeemEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, gaia_usc_v1beta1_usc_pb.RedeemEntry, 2));
};


/**
 * @param {!Array<!proto.gaia.usc.v1beta1.RedeemEntry>} value
 * @return {!proto.gaia.usc.v1beta1.GenesisState} returns this
*/
proto.gaia.usc.v1beta1.GenesisState.prototype.setRedeemEntriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.gaia.usc.v1beta1.RedeemEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gaia.usc.v1beta1.RedeemEntry}
 */
proto.gaia.usc.v1beta1.GenesisState.prototype.addRedeemEntries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.gaia.usc.v1beta1.RedeemEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gaia.usc.v1beta1.GenesisState} returns this
 */
proto.gaia.usc.v1beta1.GenesisState.prototype.clearRedeemEntriesList = function() {
  return this.setRedeemEntriesList([]);
};


goog.object.extend(exports, proto.gaia.usc.v1beta1);
