// source: gaia/usc/v1beta1/tx.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var cosmos_base_v1beta1_coin_pb = require('../../../cosmos/base/v1beta1/coin_pb.js');
goog.object.extend(proto, cosmos_base_v1beta1_coin_pb);
goog.exportSymbol('proto.gaia.usc.v1beta1.MsgMintUSC', null, global);
goog.exportSymbol('proto.gaia.usc.v1beta1.MsgMintUSCResponse', null, global);
goog.exportSymbol('proto.gaia.usc.v1beta1.MsgRedeemCollateral', null, global);
goog.exportSymbol('proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.MsgMintUSC = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gaia.usc.v1beta1.MsgMintUSC.repeatedFields_, null);
};
goog.inherits(proto.gaia.usc.v1beta1.MsgMintUSC, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.MsgMintUSC.displayName = 'proto.gaia.usc.v1beta1.MsgMintUSC';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gaia.usc.v1beta1.MsgMintUSCResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.MsgMintUSCResponse.displayName = 'proto.gaia.usc.v1beta1.MsgMintUSCResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gaia.usc.v1beta1.MsgRedeemCollateral, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.MsgRedeemCollateral.displayName = 'proto.gaia.usc.v1beta1.MsgRedeemCollateral';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.repeatedFields_, null);
};
goog.inherits(proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.displayName = 'proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gaia.usc.v1beta1.MsgMintUSC.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.MsgMintUSC.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.MsgMintUSC.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.MsgMintUSC} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.MsgMintUSC.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, ""),
    collateralAmountList: jspb.Message.toObjectList(msg.getCollateralAmountList(),
    cosmos_base_v1beta1_coin_pb.Coin.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.MsgMintUSC}
 */
proto.gaia.usc.v1beta1.MsgMintUSC.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.MsgMintUSC;
  return proto.gaia.usc.v1beta1.MsgMintUSC.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.MsgMintUSC} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.MsgMintUSC}
 */
proto.gaia.usc.v1beta1.MsgMintUSC.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 2:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.addCollateralAmount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.MsgMintUSC.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.MsgMintUSC.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.MsgMintUSC} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.MsgMintUSC.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCollateralAmountList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
};


/**
 * optional string address = 1;
 * @return {string}
 */
proto.gaia.usc.v1beta1.MsgMintUSC.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gaia.usc.v1beta1.MsgMintUSC} returns this
 */
proto.gaia.usc.v1beta1.MsgMintUSC.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated cosmos.base.v1beta1.Coin collateral_amount = 2;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.gaia.usc.v1beta1.MsgMintUSC.prototype.getCollateralAmountList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (
    jspb.Message.getRepeatedWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 2));
};


/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.gaia.usc.v1beta1.MsgMintUSC} returns this
*/
proto.gaia.usc.v1beta1.MsgMintUSC.prototype.setCollateralAmountList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.gaia.usc.v1beta1.MsgMintUSC.prototype.addCollateralAmount = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.cosmos.base.v1beta1.Coin, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gaia.usc.v1beta1.MsgMintUSC} returns this
 */
proto.gaia.usc.v1beta1.MsgMintUSC.prototype.clearCollateralAmountList = function() {
  return this.setCollateralAmountList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.MsgMintUSCResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.MsgMintUSCResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    mintedAmount: (f = msg.getMintedAmount()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.MsgMintUSCResponse}
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.MsgMintUSCResponse;
  return proto.gaia.usc.v1beta1.MsgMintUSCResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.MsgMintUSCResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.MsgMintUSCResponse}
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setMintedAmount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.MsgMintUSCResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.MsgMintUSCResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMintedAmount();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
};


/**
 * optional cosmos.base.v1beta1.Coin minted_amount = 1;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse.prototype.getMintedAmount = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 1));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.gaia.usc.v1beta1.MsgMintUSCResponse} returns this
*/
proto.gaia.usc.v1beta1.MsgMintUSCResponse.prototype.setMintedAmount = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gaia.usc.v1beta1.MsgMintUSCResponse} returns this
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse.prototype.clearMintedAmount = function() {
  return this.setMintedAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gaia.usc.v1beta1.MsgMintUSCResponse.prototype.hasMintedAmount = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.MsgRedeemCollateral.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.MsgRedeemCollateral} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uscAmount: (f = msg.getUscAmount()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateral}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.MsgRedeemCollateral;
  return proto.gaia.usc.v1beta1.MsgRedeemCollateral.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.MsgRedeemCollateral} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateral}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 2:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setUscAmount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.MsgRedeemCollateral.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.MsgRedeemCollateral} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUscAmount();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
};


/**
 * optional string address = 1;
 * @return {string}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateral} returns this
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional cosmos.base.v1beta1.Coin usc_amount = 2;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.prototype.getUscAmount = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 2));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateral} returns this
*/
proto.gaia.usc.v1beta1.MsgRedeemCollateral.prototype.setUscAmount = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateral} returns this
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.prototype.clearUscAmount = function() {
  return this.setUscAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateral.prototype.hasUscAmount = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    burnedAmount: (f = msg.getBurnedAmount()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f),
    redeemedAmountList: jspb.Message.toObjectList(msg.getRedeemedAmountList(),
    cosmos_base_v1beta1_coin_pb.Coin.toObject, includeInstance),
    completionTime: (f = msg.getCompletionTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse;
  return proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setBurnedAmount(value);
      break;
    case 2:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.addRedeemedAmount(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCompletionTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBurnedAmount();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getRedeemedAmountList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getCompletionTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional cosmos.base.v1beta1.Coin burned_amount = 1;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.getBurnedAmount = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 1));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse} returns this
*/
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.setBurnedAmount = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse} returns this
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.clearBurnedAmount = function() {
  return this.setBurnedAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.hasBurnedAmount = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated cosmos.base.v1beta1.Coin redeemed_amount = 2;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.getRedeemedAmountList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (
    jspb.Message.getRepeatedWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 2));
};


/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse} returns this
*/
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.setRedeemedAmountList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.addRedeemedAmount = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.cosmos.base.v1beta1.Coin, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse} returns this
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.clearRedeemedAmountList = function() {
  return this.setRedeemedAmountList([]);
};


/**
 * optional google.protobuf.Timestamp completion_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.getCompletionTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse} returns this
*/
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.setCompletionTime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse} returns this
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.clearCompletionTime = function() {
  return this.setCompletionTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gaia.usc.v1beta1.MsgRedeemCollateralResponse.prototype.hasCompletionTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.gaia.usc.v1beta1);
