// source: gaia/usc/v1beta1/usc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var cosmos_base_v1beta1_coin_pb = require('../../../cosmos/base/v1beta1/coin_pb.js');
goog.object.extend(proto, cosmos_base_v1beta1_coin_pb);
goog.exportSymbol('proto.gaia.usc.v1beta1.Params', null, global);
goog.exportSymbol('proto.gaia.usc.v1beta1.RedeemEntry', null, global);
goog.exportSymbol('proto.gaia.usc.v1beta1.RedeemEntryOperation', null, global);
goog.exportSymbol('proto.gaia.usc.v1beta1.RedeemingQueueData', null, global);
goog.exportSymbol('proto.gaia.usc.v1beta1.TokenMeta', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.Params = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gaia.usc.v1beta1.Params.repeatedFields_, null);
};
goog.inherits(proto.gaia.usc.v1beta1.Params, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.Params.displayName = 'proto.gaia.usc.v1beta1.Params';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.TokenMeta = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.gaia.usc.v1beta1.TokenMeta, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.TokenMeta.displayName = 'proto.gaia.usc.v1beta1.TokenMeta';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.RedeemEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gaia.usc.v1beta1.RedeemEntry.repeatedFields_, null);
};
goog.inherits(proto.gaia.usc.v1beta1.RedeemEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.RedeemEntry.displayName = 'proto.gaia.usc.v1beta1.RedeemEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gaia.usc.v1beta1.RedeemEntryOperation.repeatedFields_, null);
};
goog.inherits(proto.gaia.usc.v1beta1.RedeemEntryOperation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.RedeemEntryOperation.displayName = 'proto.gaia.usc.v1beta1.RedeemEntryOperation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.gaia.usc.v1beta1.RedeemingQueueData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.gaia.usc.v1beta1.RedeemingQueueData.repeatedFields_, null);
};
goog.inherits(proto.gaia.usc.v1beta1.RedeemingQueueData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.gaia.usc.v1beta1.RedeemingQueueData.displayName = 'proto.gaia.usc.v1beta1.RedeemingQueueData';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gaia.usc.v1beta1.Params.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.Params.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.Params.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.Params} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.Params.toObject = function(includeInstance, msg) {
  var f, obj = {
    redeemDur: (f = msg.getRedeemDur()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    maxRedeemEntries: jspb.Message.getFieldWithDefault(msg, 2, 0),
    collateralMetasList: jspb.Message.toObjectList(msg.getCollateralMetasList(),
    proto.gaia.usc.v1beta1.TokenMeta.toObject, includeInstance),
    uscMeta: (f = msg.getUscMeta()) && proto.gaia.usc.v1beta1.TokenMeta.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.Params}
 */
proto.gaia.usc.v1beta1.Params.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.Params;
  return proto.gaia.usc.v1beta1.Params.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.Params} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.Params}
 */
proto.gaia.usc.v1beta1.Params.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRedeemDur(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxRedeemEntries(value);
      break;
    case 3:
      var value = new proto.gaia.usc.v1beta1.TokenMeta;
      reader.readMessage(value,proto.gaia.usc.v1beta1.TokenMeta.deserializeBinaryFromReader);
      msg.addCollateralMetas(value);
      break;
    case 4:
      var value = new proto.gaia.usc.v1beta1.TokenMeta;
      reader.readMessage(value,proto.gaia.usc.v1beta1.TokenMeta.deserializeBinaryFromReader);
      msg.setUscMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.Params.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.Params.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.Params} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.Params.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRedeemDur();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getMaxRedeemEntries();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getCollateralMetasList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.gaia.usc.v1beta1.TokenMeta.serializeBinaryToWriter
    );
  }
  f = message.getUscMeta();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.gaia.usc.v1beta1.TokenMeta.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Duration redeem_dur = 1;
 * @return {?proto.google.protobuf.Duration}
 */
proto.gaia.usc.v1beta1.Params.prototype.getRedeemDur = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 1));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.gaia.usc.v1beta1.Params} returns this
*/
proto.gaia.usc.v1beta1.Params.prototype.setRedeemDur = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gaia.usc.v1beta1.Params} returns this
 */
proto.gaia.usc.v1beta1.Params.prototype.clearRedeemDur = function() {
  return this.setRedeemDur(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gaia.usc.v1beta1.Params.prototype.hasRedeemDur = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 max_redeem_entries = 2;
 * @return {number}
 */
proto.gaia.usc.v1beta1.Params.prototype.getMaxRedeemEntries = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.gaia.usc.v1beta1.Params} returns this
 */
proto.gaia.usc.v1beta1.Params.prototype.setMaxRedeemEntries = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated TokenMeta collateral_metas = 3;
 * @return {!Array<!proto.gaia.usc.v1beta1.TokenMeta>}
 */
proto.gaia.usc.v1beta1.Params.prototype.getCollateralMetasList = function() {
  return /** @type{!Array<!proto.gaia.usc.v1beta1.TokenMeta>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gaia.usc.v1beta1.TokenMeta, 3));
};


/**
 * @param {!Array<!proto.gaia.usc.v1beta1.TokenMeta>} value
 * @return {!proto.gaia.usc.v1beta1.Params} returns this
*/
proto.gaia.usc.v1beta1.Params.prototype.setCollateralMetasList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.gaia.usc.v1beta1.TokenMeta=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gaia.usc.v1beta1.TokenMeta}
 */
proto.gaia.usc.v1beta1.Params.prototype.addCollateralMetas = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.gaia.usc.v1beta1.TokenMeta, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gaia.usc.v1beta1.Params} returns this
 */
proto.gaia.usc.v1beta1.Params.prototype.clearCollateralMetasList = function() {
  return this.setCollateralMetasList([]);
};


/**
 * optional TokenMeta usc_meta = 4;
 * @return {?proto.gaia.usc.v1beta1.TokenMeta}
 */
proto.gaia.usc.v1beta1.Params.prototype.getUscMeta = function() {
  return /** @type{?proto.gaia.usc.v1beta1.TokenMeta} */ (
    jspb.Message.getWrapperField(this, proto.gaia.usc.v1beta1.TokenMeta, 4));
};


/**
 * @param {?proto.gaia.usc.v1beta1.TokenMeta|undefined} value
 * @return {!proto.gaia.usc.v1beta1.Params} returns this
*/
proto.gaia.usc.v1beta1.Params.prototype.setUscMeta = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gaia.usc.v1beta1.Params} returns this
 */
proto.gaia.usc.v1beta1.Params.prototype.clearUscMeta = function() {
  return this.setUscMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gaia.usc.v1beta1.Params.prototype.hasUscMeta = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.TokenMeta.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.TokenMeta.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.TokenMeta} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.TokenMeta.toObject = function(includeInstance, msg) {
  var f, obj = {
    denom: jspb.Message.getFieldWithDefault(msg, 1, ""),
    decimals: jspb.Message.getFieldWithDefault(msg, 2, 0),
    description: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.TokenMeta}
 */
proto.gaia.usc.v1beta1.TokenMeta.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.TokenMeta;
  return proto.gaia.usc.v1beta1.TokenMeta.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.TokenMeta} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.TokenMeta}
 */
proto.gaia.usc.v1beta1.TokenMeta.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDenom(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDecimals(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.TokenMeta.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.TokenMeta.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.TokenMeta} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.TokenMeta.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDenom();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDecimals();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string denom = 1;
 * @return {string}
 */
proto.gaia.usc.v1beta1.TokenMeta.prototype.getDenom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gaia.usc.v1beta1.TokenMeta} returns this
 */
proto.gaia.usc.v1beta1.TokenMeta.prototype.setDenom = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 decimals = 2;
 * @return {number}
 */
proto.gaia.usc.v1beta1.TokenMeta.prototype.getDecimals = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.gaia.usc.v1beta1.TokenMeta} returns this
 */
proto.gaia.usc.v1beta1.TokenMeta.prototype.setDecimals = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.gaia.usc.v1beta1.TokenMeta.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.gaia.usc.v1beta1.TokenMeta} returns this
 */
proto.gaia.usc.v1beta1.TokenMeta.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gaia.usc.v1beta1.RedeemEntry.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.RedeemEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.RedeemEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.RedeemEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.RedeemEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, ""),
    operationsList: jspb.Message.toObjectList(msg.getOperationsList(),
    proto.gaia.usc.v1beta1.RedeemEntryOperation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.RedeemEntry}
 */
proto.gaia.usc.v1beta1.RedeemEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.RedeemEntry;
  return proto.gaia.usc.v1beta1.RedeemEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.RedeemEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.RedeemEntry}
 */
proto.gaia.usc.v1beta1.RedeemEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 2:
      var value = new proto.gaia.usc.v1beta1.RedeemEntryOperation;
      reader.readMessage(value,proto.gaia.usc.v1beta1.RedeemEntryOperation.deserializeBinaryFromReader);
      msg.addOperations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.RedeemEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.RedeemEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.RedeemEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.RedeemEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOperationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.gaia.usc.v1beta1.RedeemEntryOperation.serializeBinaryToWriter
    );
  }
};


/**
 * optional string address = 1;
 * @return {string}
 */
proto.gaia.usc.v1beta1.RedeemEntry.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.gaia.usc.v1beta1.RedeemEntry} returns this
 */
proto.gaia.usc.v1beta1.RedeemEntry.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated RedeemEntryOperation operations = 2;
 * @return {!Array<!proto.gaia.usc.v1beta1.RedeemEntryOperation>}
 */
proto.gaia.usc.v1beta1.RedeemEntry.prototype.getOperationsList = function() {
  return /** @type{!Array<!proto.gaia.usc.v1beta1.RedeemEntryOperation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.gaia.usc.v1beta1.RedeemEntryOperation, 2));
};


/**
 * @param {!Array<!proto.gaia.usc.v1beta1.RedeemEntryOperation>} value
 * @return {!proto.gaia.usc.v1beta1.RedeemEntry} returns this
*/
proto.gaia.usc.v1beta1.RedeemEntry.prototype.setOperationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.gaia.usc.v1beta1.RedeemEntryOperation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.gaia.usc.v1beta1.RedeemEntryOperation}
 */
proto.gaia.usc.v1beta1.RedeemEntry.prototype.addOperations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.gaia.usc.v1beta1.RedeemEntryOperation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gaia.usc.v1beta1.RedeemEntry} returns this
 */
proto.gaia.usc.v1beta1.RedeemEntry.prototype.clearOperationsList = function() {
  return this.setOperationsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.RedeemEntryOperation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.RedeemEntryOperation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.toObject = function(includeInstance, msg) {
  var f, obj = {
    creationHeight: jspb.Message.getFieldWithDefault(msg, 1, 0),
    completionTime: (f = msg.getCompletionTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    collateralAmountList: jspb.Message.toObjectList(msg.getCollateralAmountList(),
    cosmos_base_v1beta1_coin_pb.Coin.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.RedeemEntryOperation}
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.RedeemEntryOperation;
  return proto.gaia.usc.v1beta1.RedeemEntryOperation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.RedeemEntryOperation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.RedeemEntryOperation}
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreationHeight(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCompletionTime(value);
      break;
    case 3:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.addCollateralAmount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.RedeemEntryOperation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.RedeemEntryOperation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreationHeight();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getCompletionTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCollateralAmountList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 creation_height = 1;
 * @return {number}
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.getCreationHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.gaia.usc.v1beta1.RedeemEntryOperation} returns this
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.setCreationHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp completion_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.getCompletionTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.gaia.usc.v1beta1.RedeemEntryOperation} returns this
*/
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.setCompletionTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.gaia.usc.v1beta1.RedeemEntryOperation} returns this
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.clearCompletionTime = function() {
  return this.setCompletionTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.hasCompletionTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated cosmos.base.v1beta1.Coin collateral_amount = 3;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.getCollateralAmountList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (
    jspb.Message.getRepeatedWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 3));
};


/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.gaia.usc.v1beta1.RedeemEntryOperation} returns this
*/
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.setCollateralAmountList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.addCollateralAmount = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.cosmos.base.v1beta1.Coin, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gaia.usc.v1beta1.RedeemEntryOperation} returns this
 */
proto.gaia.usc.v1beta1.RedeemEntryOperation.prototype.clearCollateralAmountList = function() {
  return this.setCollateralAmountList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.prototype.toObject = function(opt_includeInstance) {
  return proto.gaia.usc.v1beta1.RedeemingQueueData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.gaia.usc.v1beta1.RedeemingQueueData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.toObject = function(includeInstance, msg) {
  var f, obj = {
    addressesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.gaia.usc.v1beta1.RedeemingQueueData}
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.gaia.usc.v1beta1.RedeemingQueueData;
  return proto.gaia.usc.v1beta1.RedeemingQueueData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.gaia.usc.v1beta1.RedeemingQueueData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.gaia.usc.v1beta1.RedeemingQueueData}
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAddresses(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.gaia.usc.v1beta1.RedeemingQueueData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.gaia.usc.v1beta1.RedeemingQueueData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddressesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string addresses = 1;
 * @return {!Array<string>}
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.prototype.getAddressesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.gaia.usc.v1beta1.RedeemingQueueData} returns this
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.prototype.setAddressesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.gaia.usc.v1beta1.RedeemingQueueData} returns this
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.prototype.addAddresses = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.gaia.usc.v1beta1.RedeemingQueueData} returns this
 */
proto.gaia.usc.v1beta1.RedeemingQueueData.prototype.clearAddressesList = function() {
  return this.setAddressesList([]);
};


goog.object.extend(exports, proto.gaia.usc.v1beta1);
